# 应用名称
spring:
  datasource:
    username: root
    url: jdbc:mysql://47.101.143.219:3308/covid?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: 123654
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package:
    com.liu.covid.entity